In [41]:
import pandas as pd

df = pd.read_csv('https://www.gov.br/anac/pt-br/assuntos/dados-e-estatisticas/percentuais-de-atrasos-e-cancelamentos-2/2024/vra_2024_07.csv', sep=';')

## Entendimento de colunas
- Código DI: Indica a etapa do voo realizada, as explicações de cada etapa podem ser encontradas em um ofício do Diário oficial da União, que está salvo em PDF nesse projeto.
- Código Tipo Linha: 
- Número Voo:

In [44]:

codigos_di_manter = (df['Código DI'].isin(['0', '2']))
df = df[codigos_di_manter]
# df['Número Voo'].value_counts()# .describe()
# codigo_di_map = {'0': 'Padrão',
#     '1': 'Etapa extra, tem transporte de carga, mas não era esperado existir essa etapa',
#     '2': 'Etapa extra, tem transporte de carga, mas não era esperado existir essa etapa',
#     '3': 'Etapa remunerada que não concretizou o transporte',
#     '6': 'Não remunerados sem transporte de carga',
#     '7': 'Voo fretado',
#     '9': 'Etapa de voo Charter',
#     'D': 'Voo utilizado para transporte de objetos de um segundo voo',
#     'E': 'Voo grátis oferecido pela compainha áerea'}

## Análise valores nulos
- Quase todo Voo com partida Real ou Chegada Real nula, foram cancelados

In [52]:
# Análise valores nulos
# Identificar se existe alguma correlação entre esses valores nulos e locais espécificos
display(df.isna().sum())
display(df[(df['Partida Real'].isna()) | ((df['Chegada Real'].isna()))].value_counts('Situação Voo'))

Sigla ICAO Empresa Aérea           0
Número Voo                         0
Código DI                          0
Código Tipo Linha                  0
Sigla ICAO Aeroporto Origem        0
Partida Prevista                 863
Partida Real                    3488
Sigla ICAO Aeroporto Destino       0
Chegada Prevista                 863
Chegada Real                    3489
Situação Voo                       0
dtype: int64

Situação Voo
CANCELADO    3488
REALIZADO       1
Name: count, dtype: int64

## Tratamento dos dados

In [55]:
df = df.dropna(subset=['Partida Prevista', 'Chegada Prevista'])
df = df.drop(columns=['Código DI', 'Código Tipo Linha'])

# Removendo voos realizados sem informação de partida e chegada
df = df[~(((df['Partida Real'].isna()) | ((df['Chegada Real'].isna()))) & (df['Situação Voo'] == 'REALIZADO'))]

In [57]:
df

,Sigla ICAO Empresa Aérea,Número Voo,Sigla ICAO Aeroporto Origem,Partida Prevista,Partida Real,Sigla ICAO Aeroporto Destino,Chegada Prevista,Chegada Real,Situação Voo
0,AAL,904,SBGL,01/07/2024 23:00,01/07/2024 22:58,KMIA,02/07/2024 07:35,02/07/2024 07:34,REALIZADO
1,AAL,905,KMIA,01/07/2024 21:55,01/07/2024 21:31,SBGL,02/07/2024 06:00,02/07/2024 05:55,REALIZADO
2,AAL,906,SBGR,01/07/2024 23:15,01/07/2024 23:11,KMIA,02/07/2024 07:45,02/07/2024 07:21,REALIZADO
3,AAL,929,KMIA,01/07/2024 20:50,02/07/2024 12:01,SBGR,02/07/2024 05:15,02/07/2024 21:15,REALIZADO
4,AAL,930,SBGR,01/07/2024 21:25,01/07/2024 21:09,KMIA,02/07/2024 05:55,02/07/2024 05:34,REALIZADO
...,...,...,...,...,...,...,...,...,...
87801,UPS,417,SBKP,30/07/2024 10:30,30/07/2024 10:22,SEQM,30/07/2024 16:05,30/07/2024 16:21,REALIZADO
87802,UPS,417,SEQM,30/07/2024 17:35,30/07/2024 17:57,KMIA,30/07/2024 21:30,30/07/2024 21:55,REALIZADO
87803,UPS,410,KMIA,31/07/2024 10:20,31/07/2024 11:06,SBKP,31/07/2024 18:15,31/07/2024 18:35,REALIZADO
87804,UPS,415,SBKP,31/07/2024 10:20,31/07/2024 10:07,SEQM,31/07/2024 15:55,31/07/2024 15:51,REALIZADO
87805,UPS,415,SEQM,31/07/2024 17:35,31/07/2024 17:22,KMIA,31/07/2024 21:30,31/07/2024 21:23,REALIZADO

## Análise Exploratória